# include <iostream>
using namespace std;
main(){
system ("color D7"); 
cout<<"  U  U  N   NN  I V       V EEEEE  RRRRRR  SSSSSS I TTTTTTT Y   Y        AAAAAA  DDDDDD    MM   MM  I   SSSSSS  SSSSSS   I    OOOO    NN    N                                           "<<endl;
cout<<"  U  U  N  N N  I  V     V  E      R    R SS      I    T     Y Y         A    A  D     D   M M M M  I  SS      SS        I  OO    OO  N N   N                                "<<endl;
cout<<"  U  U  N N  N  I   V   V   EEEE   RRRRRR  SSSS   I    T      Y          AAAAAA  D     DD  M  M  M  I   SSSS    SSSSS    I OO      OO N  N  N                                    "<<endl;
cout<<"  U  U  N N  N  I    V V    E      R  R       SS  I    T      Y          A    A  D     D   M     M  I       SS       SS  I  OO    OO  N   N N                                   "<<endl;
cout<<"  UUUU  NN   N  I     V     EEEEE  R    R SSSSS   I    T      Y          A    A  DDDDDD    M     M  I  SSSSSS   SSSSSS   I    OOOO    N    NN                                          "<<endl;
cout<<"                                                                                                                                                                          "<<endl;
cout<<"                                                                                                                                                              "<<endl;
cout<<"  MM    MM      AA      NN    N      AA       GGGGGGG  EEEEE  MM   MM  EEEEE  NN    N TTTTTTT        SSSSSS  Y   Y   SSSSSS  TTTTTTT EEEEEE  MM    MM                                                                               "<<endl;
cout<<"  M M  M M     A  A     N N   N     A  A    GG         E      M M M M  E      N N   N    T          SS        Y Y   SS          T    E       M M  M M                                          "<<endl;
cout<<"  M  MM  M    AAAAAA    N  N  N    AAAAAA  GG     GGG  EEEEE  M  MM M  EEEEE  N  N  N    T           SSSS      Y     SSSSS      T    EEEEEE  M  MM  M                                                            "<<endl;
cout<<"  M      M   A      A   N   N N   A      A  GG      G  E      M     M  E      N   N N    T               SS    Y          SS    T    E       M      M                                  "<<endl;
cout<<"  M      M  A        A  N    NN  A        A    GGGGGG  EEEEE  M     M  EEEEE  N    NN    T          SSSSSS     Y     SSSSSS     T    EEEEEE  M      M                                                             "<<endl;
}
